# Generated by Django 5.1 on 2024-09-11 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('renter_name', models.CharField(max_length=255)),
                ('renter_email', models.EmailField(max_length=254)),
                ('rental_date', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.bike')),
            ],
        ),
    ]
