# Generated by Django 5.1 on 2024-09-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userqw',
        ),
    ]
