# Generated by Django 5.1 on 2024-09-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_userqw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userqw',
            new_name='User',
        ),
    ]
