# Generated by Django 5.1 on 2024-09-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_userqw_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('bike_model', models.CharField(choices=[('PANIGALE V4', 'PANIGALE V4'), ('ROADSTER SS', 'ROADSTER SS'), ('S1000RR', 'S1000RR'), ('STREET TRIPLE', 'STREET TRIPLE'), ('FIREBLADE RR', 'FIREBLADE RR')], max_length=50)),
                ('booking_date', models.DateField()),
                ('rental_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
